/*
Probatio addresses and definitions:
*/

#define BLOCK_DUAL_BUTTONS_1 16
#define SIZE_BLOCK_DUAL_BUTTONS_1 2

#define BLOCK_DUAL_BUTTONS_2 17	
#define SIZE_BLOCK_DUAL_BUTTONS_2 2

#define BLOCK_QUAD_BUTTONS_1 20
#define SIZE_BLOCK_QUAD_BUTTONS_1 4

#define BLOCK_QUAD_BUTTONS_2 21
#define SIZE_BLOCK_QUAD_BUTTONS_2 4

#define BLOCK_CHERRIES_1 28
#define SIZE_BLOCK_CHERRIES_1 4

#define BLOCK_TAP_1 36
#define SIZE_BLOCK_TAP_1 1

#define BLOCK_DUAL_PISTONS_1 40
#define SIZE_BLOCK_DUAL_PISTONS_1 2

#define BLOCK_QUAD_POTS_1 44
#define SIZE_BLOCK_QUAD_POTS_1 4

#define BLOCK_QUAD_POTS_2 45
#define SIZE_BLOCK_QUAD_POTS_2 4

#define BLOCK_DOF4_JOYSTICK_1 62
#define SIZE_BLOCK_DOF4_JOYSTICK_1 4

#define BLOCK_ROTARY_1 64
#define SIZE_BLOCK_ROTARY_1 2

#define BLOCK_ROTARY_2 65
#define SIZE_BLOCK_ROTARY_2 2

#define BLOCK_DEBUG 80
#define SIZE_BLOCK_DEBUG 4

#define QUANTITY_BLOCKS 13
#define BUFFER_SIZE 39