
/*
Probatio addresses and definitions
 */

#define BUFFER_SIZE 44
#define QUANTITY_BLOCKS 14
#define BLOCK_BELLOWS 50
#define BLOCK_BREATH 51
#define BLOCK_CRANK 45
#define BLOCK_DEBUG 99
#define BLOCK_JOYSTICK 48
#define BLOCK_ONETAP 52
#define BLOCK_TWOPOTS 47
#define BLOCK_RESTOUCH 49
#define BLOCK_THREETAPS 53
#define BLOCK_TURNTABLE 46
#define BLOCK_TWOBUTTONS1 24
#define BLOCK_TWOBUTTONS2 25
#define BLOCK_TWOBUTTONS3 26
#define BLOCK_TWOBUTTONS4 27
#define SIZE_BLOCK_BELLOWS 1
#define SIZE_BLOCK_BREATH 1
#define SIZE_BLOCK_CRANK 2
#define SIZE_BLOCK_DEBUG 4
#define SIZE_BLOCK_JOYSTICK 2
#define SIZE_BLOCK_ONETAP 1
#define SIZE_BLOCK_TWOPOTS 2
#define SIZE_BLOCK_RESTOUCH 2
#define SIZE_BLOCK_THREETAPS 3
#define SIZE_BLOCK_TURNTABLE 2
#define SIZE_BLOCK_TWOBUTTONS1 2
#define SIZE_BLOCK_TWOBUTTONS2 2
#define SIZE_BLOCK_TWOBUTTONS3 2
#define SIZE_BLOCK_TWOBUTTONS4 2

