/*
Probatio addresses and definitions:
*/

#define BLOCK_DUAL_BUTTONS_1 16
#define SIZE_BLOCK_DUAL_BUTTONS_1 2

#define BLOCK_OBSF_24 26
#define SIZE_BLOCK_OBSF_24 1

#define BLOCK_OBSF_30 27
#define SIZE_BLOCK_OBSF_30 1

#define BLOCK_CHERRIES_1 28
#define SIZE_BLOCK_CHERRIES_1 4

#define BLOCK_DUAL_POTS_1 32
#define SIZE_BLOCK_DUAL_POTS_1 2

#define BLOCK_TAP_1 36
#define SIZE_BLOCK_TAP_1 1

#define BLOCK_TAP_2 37
#define SIZE_BLOCK_TAP_2 1

#define BLOCK_DUAL_PISTONS_1 40
#define SIZE_BLOCK_DUAL_PISTONS_1 2

#define BLOCK_JOYSTICK_1 42
#define SIZE_BLOCK_JOYSTICK_1 3

#define BLOCK_FOUR_PISTONS_1 58
#define SIZE_BLOCK_FOUR_PISTONS_1 4

#define BLOCK_FOUR_THUMBS_1 60
#define SIZE_BLOCK_FOUR_THUMBS_1 4

#define BLOCK_DOF4_JOYSTICK_1 62
#define SIZE_BLOCK_DOF4_JOYSTICK_1 4

#define BLOCK_DOF4_JOYSTICK_2 63
#define SIZE_BLOCK_DOF4_JOYSTICK_2 4

#define BLOCK_CRANK_1 64
#define SIZE_BLOCK_CRANK_1 2

#define BLOCK_DIAL_1 68
#define SIZE_BLOCK_DIAL_1 2

#define BLOCK_DEBUG 80
#define SIZE_BLOCK_DEBUG 4

#define QUANTITY_BLOCKS 16
#define BUFFER_SIZE 59